from services.services import loginFuncionario,mostrarFuncionarios,cadastrarFuncionarios,cadastrarServicos,relacionarServico,mostrarServicos,mostrarAgendaWeb,pesquisarClienteWeb

mostrarAgendaWeb(1,"20/05/2026")