"""initial

Revision ID: aa441ad50823
Revises: 
Create Date: 2026-07-24 02:19:38.703409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa441ad50823'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_de_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('funcao', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_de_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('duracao_min', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_de_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamentos',
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor_pago', sa.Integer(), nullable=True),
    sa.Column('forma_pagamento', sa.String(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('confirmado', 'cancelado', 'ocupado', name='status_type'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_de_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos_agendamentos',
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_de_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicos_agendamentos')
    op.drop_table('agendamentos')
    op.drop_table('servicos')
    op.drop_table('funcionarios')
    op.drop_table('clientes')
    # ### end Alembic commands ###
